export const postings = [
  {
    pid: "0",
    img: "/assets/google.svg",
    company: "Google",
    companyRating: 4.3,
    title: "Full Stack Developer 1",
    specialisation: "Fullstack",
    createdAt: "01-02-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Java", "SQL", "Golang"],
  },
  {
    pid: "1",
    img: "/assets/facebook.svg",
    company: "Facebook",
    companyRating: null,
    title: "Full Stack Developer 2",
    specialisation: "Fullstack",
    createdAt: "01-05-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Java", "SQL"],
  },
  {
    pid: "2",
    img: "/assets/astar.svg",
    company: "A*STAR Agency for Science, Technology and Research",
    companyRating: 3,
    title:
      "Data Engineer / Data Engineer Lead / Lead Developer / Lead Product Manager 3",
    specialisation: "Data Analyst",
    createdAt: "05-25-2023",
    location: "Malaysia",
    currency: "RM",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Python", "SQL", "AWS"],
  },
  {
    pid: "3",
    img: "/assets/ocbc.svg",
    company: "OCBC",
    companyRating: 5,
    title:
      "Data Science Analyst ... This is a super long job title ... extremely extremely long 4",
    specialisation: "Data Sci",
    createdAt: "07-21-2023",
    location: "Indonesia",
    currency: null,
    salaryMin: null,
    salaryMax: null,
    skills: ["Python"],
  },
  {
    pid: "4",
    img: "/assets/dbs.svg",
    company: "DBS Bank",
    companyRating: null,
    title: "Data Analyst",
    specialisation: "Data Analyst 5",
    createdAt: "08-19-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 3000,
    salaryMax: 4000,
    skills: [
      "VBA",
      "PowerBI",
      "SQL",
      "Python",
      "R",
      "Matlab",
      "Analytics",
      "Machine Learning",
    ],
  },
  {
    pid: "5",
    img: "/assets/google.svg",
    company: "Google",
    companyRating: 4.3,
    title: "Full Stack Developer 6",
    specialisation: "Fullstack",
    createdAt: "01-02-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Java", "SQL", "Golang"],
  },
  {
    pid: "6",
    img: "/assets/facebook.svg",
    company: "Facebook",
    companyRating: null,
    title: "Full Stack Developer 7",
    specialisation: "Fullstack",
    createdAt: "01-05-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Java", "SQL"],
  },
  {
    pid: "7",
    img: "/assets/astar.svg",
    company: "A*STAR Agency for Science, Technology and Research",
    companyRating: 3,
    title:
      "Data Engineer / Data Engineer Lead / Lead Developer / Lead Product Manager 8",
    specialisation: "Data Analyst",
    createdAt: "05-25-2023",
    location: "Malaysia",
    currency: "RM",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Python", "SQL", "AWS"],
  },
  {
    pid: "8",
    img: "/assets/ocbc.svg",
    company: "OCBC",
    companyRating: 5,
    title: "Data Science Analyst 9",
    specialisation: "Data Sci",
    createdAt: "07-21-2023",
    location: "Indonesia",
    currency: null,
    salaryMin: null,
    salaryMax: null,
    skills: ["Java"],
  },
  {
    pid: "9",
    img: "/assets/dbs.svg",
    company: "DBS Bank",
    companyRating: null,
    title: "Data Analyst 10",
    specialisation: "Data Analyst",
    createdAt: "08-19-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 3000,
    salaryMax: 4000,
    skills: [
      "VBA",
      "PowerBI",
      "SQL",
      "Python",
      "R",
      "Matlab",
      "Analytics",
      "Machine Learning",
    ],
  },
  {
    pid: "10",
    img: "/assets/google.svg",
    company: "Google",
    companyRating: 4.3,
    title: "Full Stack Developer 11",
    specialisation: "Fullstack",
    createdAt: "01-02-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Java", "SQL", "Golang"],
  },
  {
    pid: "11",
    img: "/assets/facebook.svg",
    company: "Facebook",
    companyRating: null,
    title: "Full Stack Developer 12",
    specialisation: "Fullstack",
    createdAt: "01-05-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Java", "SQL"],
  },
  {
    pid: "12",
    img: "/assets/astar.svg",
    company: "A*STAR Agency for Science, Technology and Research",
    companyRating: 3,
    title:
      "Data Engineer / Data Engineer Lead / Lead Developer / Lead Product Manager 13",
    specialisation: "Data Analyst",
    createdAt: "05-25-2023",
    location: "Malaysia",
    currency: "RM",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Python", "SQL", "AWS"],
  },
  {
    pid: "13",
    img: "/assets/ocbc.svg",
    company: "OCBC",
    companyRating: 5,
    title: "Data Science Analyst 14",
    specialisation: "Data Sci",
    createdAt: "07-21-2023",
    location: "Indonesia",
    currency: null,
    salaryMin: null,
    salaryMax: null,
    skills: ["SQL"],
  },
  {
    pid: "14",
    img: "/assets/dbs.svg",
    company: "DBS Bank",
    companyRating: null,
    title: "Data Analyst 15",
    specialisation: "Data Analyst",
    createdAt: "08-19-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 3000,
    salaryMax: 4000,
    skills: [
      "VBA",
      "PowerBI",
      "SQL",
      "Python",
      "R",
      "Matlab",
      "Analytics",
      "Machine Learning",
    ],
  },
  {
    pid: "15",
    img: "/assets/google.svg",
    company: "Google",
    companyRating: 4.3,
    title: "Full Stack Developer 16",
    specialisation: "Fullstack",
    createdAt: "01-02-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Java", "SQL", "Golang"],
  },
  {
    pid: "16",
    img: "/assets/facebook.svg",
    company: "Facebook",
    companyRating: null,
    title: "Full Stack Developer 17",
    specialisation: "Fullstack",
    createdAt: "01-05-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Java", "SQL"],
  },
  {
    pid: "17",
    img: "/assets/astar.svg",
    company: "A*STAR Agency for Science, Technology and Research",
    companyRating: 3,
    title:
      "Data Engineer / Data Engineer Lead / Lead Developer / Lead Product Manager 18",
    specialisation: "Data Analyst",
    createdAt: "05-25-2023",
    location: "Malaysia",
    currency: "RM",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Python", "SQL", "AWS"],
  },
  {
    pid: "18",
    img: "/assets/ocbc.svg",
    company: "OCBC",
    companyRating: 5,
    title:
      "Data Science Analyst ... This is a super long job title ... extremely extremely long 19",
    specialisation: "Data Sci",
    createdAt: "07-21-2023",
    location: "Indonesia",
    currency: null,
    salaryMin: null,
    salaryMax: null,
    skills: ["Python"],
  },
  {
    pid: "19",
    img: "/assets/dbs.svg",
    company: "DBS Bank",
    companyRating: null,
    title: "Data Analyst 20",
    specialisation: "Data Analyst",
    createdAt: "08-19-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 3000,
    salaryMax: 4000,
    skills: [
      "VBA",
      "PowerBI",
      "SQL",
      "Python",
      "R",
      "Matlab",
      "Analytics",
      "Machine Learning",
    ],
  },
  {
    pid: "20",
    img: "/assets/google.svg",
    company: "Google",
    companyRating: 4.3,
    title: "Full Stack Developer 21",
    specialisation: "Fullstack",
    createdAt: "01-02-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Java", "SQL", "Golang"],
  },
  {
    pid: "21",
    img: "/assets/facebook.svg",
    company: "Facebook",
    companyRating: null,
    title: "Full Stack Developer 22",
    specialisation: "Fullstack",
    createdAt: "01-05-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Java", "SQL"],
  },
  {
    pid: "22",
    img: "/assets/astar.svg",
    company: "A*STAR Agency for Science, Technology and Research",
    companyRating: 3,
    title:
      "Data Engineer / Data Engineer Lead / Lead Developer / Lead Product Manager 23",
    specialisation: "Data Analyst",
    createdAt: "05-25-2023",
    location: "Malaysia",
    currency: "RM",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Python", "SQL", "AWS"],
  },
  {
    pid: "23",
    img: "/assets/ocbc.svg",
    company: "OCBC",
    companyRating: 5,
    title: "Data Science Analyst 24",
    specialisation: "Data Sci",
    createdAt: "07-21-2023",
    location: "Indonesia",
    currency: null,
    salaryMin: null,
    salaryMax: null,
    skills: ["Java"],
  },
  {
    pid: "24",
    img: "/assets/dbs.svg",
    company: "DBS Bank",
    companyRating: null,
    title: "Data Analyst 25",
    specialisation: "Data Analyst",
    createdAt: "08-19-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 3000,
    salaryMax: 4000,
    skills: [
      "VBA",
      "PowerBI",
      "SQL",
      "Python",
      "R",
      "Matlab",
      "Analytics",
      "Machine Learning",
    ],
  },
  {
    pid: "25",
    img: "/assets/google.svg",
    company: "Google",
    companyRating: 4.3,
    title: "Full Stack Developer 26",
    specialisation: "Fullstack",
    createdAt: "01-02-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Java", "SQL", "Golang"],
  },
  {
    pid: "26",
    img: "/assets/facebook.svg",
    company: "Facebook",
    companyRating: null,
    title: "Full Stack Developer 27",
    specialisation: "Fullstack",
    createdAt: "01-05-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Java", "SQL"],
  },
  {
    pid: "27",
    img: "/assets/astar.svg",
    company: "A*STAR Agency for Science, Technology and Research",
    companyRating: 3,
    title:
      "Data Engineer / Data Engineer Lead / Lead Developer / Lead Product Manager 28",
    specialisation: "Data Analyst",
    createdAt: "05-25-2023",
    location: "Malaysia",
    currency: "RM",
    salaryMin: 5000,
    salaryMax: 7000,
    skills: ["Python", "SQL", "AWS"],
  },
  {
    pid: "28",
    img: "/assets/ocbc.svg",
    company: "OCBC",
    companyRating: 5,
    title: "Data Science Analyst 29",
    specialisation: "Data Sci",
    createdAt: "07-21-2023",
    location: "Indonesia",
    currency: null,
    salaryMin: null,
    salaryMax: null,
    skills: ["SQL"],
  },
  {
    pid: "29",
    img: "/assets/dbs.svg",
    company: "DBS Bank",
    companyRating: null,
    title: "Data Analyst 30",
    specialisation: "Data Analyst",
    createdAt: "08-19-2023",
    location: "Singapore",
    currency: "S$",
    salaryMin: 3000,
    salaryMax: 4000,
    skills: [
      "VBA",
      "PowerBI",
      "SQL",
      "Python",
      "R",
      "Matlab",
      "Analytics",
      "Machine Learning",
    ],
  },
];
